server:
  port: 8080

spring:
  application:
    name: mybatistudy
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root

mybatis-plus:
  type-aliases-package: com.maffy.pojo    # 别名扫描包（xml返回类型不用写全限定名）
  mapper-locations: "classpath*:/mapper/**/*.xml"    # Mapper.xml文件地址，默认值
  configuration:
    map-underscore-to-camel-case: true   # 是否开启下划线驼峰映射
    cache-enabled: false   # 是否开启二级缓存
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      id-type: auto   # id生成策略：默认是assign_id 雪花算法
      update-strategy: not_null    # 更新策略：只更新非空字段
      logic-delete-field: deleted  # 逻辑删除对应字段
      logic-delete-value: 1        # 逻辑删除值
      logic-not-delete-value: 0    # 逻辑没删除值

logging:
  level:
    root: info
    com.maffy: warn
    com.maffy.mapper: debug
  pattern:
    console: '[%level] %blue(%d{HH:mm:ss.SSS}) %cyan([%thread]) %boldGreen(%logger{15}) - %msg %n'

knife4j:
  enable: true
  openapi:
    title: 用户管理接口文档
    description: "用户管理接口文档"
    email: qiangfei.ma@qq.com
    concat: maffy
    url: https://www.maffy.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.maffy.controller
